---
title: "An introduction to the cpop package"
author:
- name: Kevin Y.X. Wang
  affiliation: School of Mathematics and Statistics, The University of Sydney, Australia
output:
  BiocStyle::html_document:
    toc_float: true
package: BiocStyle
vignette: >
  %\VignetteIndexEntry{cpop}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
  
```{r}
library(CPOP)
```

# Load melanoma data 
```{r}
data(melanoma_example, package = "CPOP")
```


```{r}
library(mvtnorm)
set.seed(1234)
tcga_x = mvtnorm::rmvnorm(n = length(list_melanoma_samples$tcga), 
                        mean = list_melanoma_means$tcga, 
                        sigma = list_melanoma_sigma$tcga)
tcga_z = CPOP::pairwise_col_diff(tcga_x)

tcga_beta = rbeta(ncol(tcga_z), shape1 = 0.1, shape2 = 0.5)
hist(tcga_beta)
tcga_y = tcga_z %*% tcga_beta
###################################################
sweden_x = mvtnorm::rmvnorm(n = length(list_melanoma_samples$sweden), 
                        mean = list_melanoma_means$sweden, 
                        sigma = list_melanoma_sigma$sweden)

sweden_beta = rbeta(ncol(tcga_z), shape1 = 0.1, shape2 = 0.5)
sweden_z = CPOP::pairwise_col_diff(sweden_x)
sweden_y = sweden_z %*% sweden_beta
```


```{r}
plot(tcga_beta, sweden_beta)
```


```{r}
naive_lasso = function(x, y, family){
  glmnet::cv.glmnet(x = x, y = y, family = family)
}

naive_lasso_tcga = naive_lasso(x = tcga_z, y = tcga_y, family = "gaussian")
CPOP::get_lasso_coef(naive_lasso_tcga, s = "lambda.min")
naive_lasso_tcga_pred_sweden = predict(naive_lasso_tcga, newx = sweden_z, s = "lambda.min")

plot(sweden_y, naive_lasso_tcga_pred_sweden)
abline(a = 0, b = 1, col = "red")
####################
####################
```


```{r}
w = CPOP::compute_weights(tcga_z, sweden_z)
tcga_sweden_cpop = CPOP::cpop_model(z1 = tcga_z, 
                                    z2 = sweden_z, 
                                    y1 = tcga_y, 
                                    y2 = sweden_y, w = w, n_features = 100, alpha = 1, family = "gaussian")

plot(CPOP::predict_cpop(tcga_sweden_cpop, newz = sweden_z, model_number = 1),
     sweden_y)
abline(a = 0, b = 1, col = "red")

CPOP::plot_cpop_coef(tcga_sweden_cpop, type = "text")
CPOP::plot_cpop_coef(tcga_sweden_cpop, type = "bar")
```



<!-- ```{r} -->
<!-- library(HDCI) -->
<!-- tcga_sweden_escv = HDCI::escv.glmnet(x = tcga_z,  -->
<!--                                      y = tcga_y, family = "gaussian") -->

<!-- get_lasso_coef(tcga_sweden_escv$glmnet.fit, s = tcga_sweden_escv$lambda.escv, tibble = TRUE) -->
<!-- naive_lasso_tcga_pred_sweden_escv = predict(tcga_sweden_escv$glmnet.fit,  -->
<!--                                             newx = sweden_z, s = tcga_sweden_escv$lambda.escv) -->

<!-- plot(sweden_y, naive_lasso_tcga_pred_sweden_escv) -->
<!-- abline(a = 0, b = 1, col = "red") -->
<!-- ``` -->


<!-- ```{r} -->
<!-- set.seed(1) -->
<!-- n = 1000 -->
<!-- p = 100 -->

<!-- library(Matrix) -->
<!-- library(mvtnorm) -->
<!-- library(dplyr) -->


<!-- sigma1 = (matrix(rnorm(p * p, mean = 1, sd = 1), nrow = p, ncol = p) %>% Matrix::nearPD())$mat %>% as.matrix() %>% cov2cor() -->
<!-- sigma2 = (matrix(rnorm(p * p, mean = 5, sd = 1), nrow = p, ncol = p) %>% Matrix::nearPD())$mat %>% as.matrix() %>% cov2cor() -->
<!-- # x1 = matrix(rnorm(n * p, mean = 0, sd = 1), nrow = n, ncol = p) -->
<!-- # x2 = x1 + 0.2 -->
<!-- x1 = mvtnorm::rmvnorm(n = n, sigma = sigma1) -->
<!-- x2 = mvtnorm::rmvnorm(n = n, sigma = sigma2) -->

<!-- sigma1[1:5, 1:5] -->
<!-- sigma2[1:5, 1:5] -->

<!-- colnames(x1) = colnames(x2) = paste0("X", 1:p) -->
<!-- k = 2 -->
<!-- beta = c(rep(0.4, k), rep(0, p - k)) -->

<!-- expit = function(x) 1/(1+exp(-x)) -->
<!-- y1 = rbinom(n, 1, prob = expit(x1 %*% beta)) -->
<!-- y2 = rbinom(n, 1, prob = expit(x2 %*% beta)) -->

<!-- table(y1) -->
<!-- table(y2) -->

<!-- plot(colMeans(x1), colMeans(x2)) -->
<!-- CPOP::identityDist(colMeans(x1), colMeans(x2)) -->
<!-- abline(a = 0, b = 1, col = "red") -->


<!-- # z1 = pairwise_col_diff(x1) -->
<!-- # z2 = pairwise_col_diff(x2) -->
<!-- w = compute_weights(x1, x2) -->
<!-- nIter = 20 -->

<!-- cpop1_result = cpop1(x1, x2, y1, y2, w, nIter = 20, alpha = 1, s = "lambda.min") -->

<!-- plot(colMeans(x1)[cpop1_result], colMeans(x2)[cpop1_result]) -->
<!-- CPOP::identityDist(colMeans(x1)[cpop1_result], colMeans(x2)[cpop1_result]) -->
<!-- abline(a = 0, b = 1, col = "red") -->



<!-- s = "lambda.min" -->

<!-- cpop2_result = cpop2_sign(x1, x2, y1, y2, cpop1_result = cpop1_result, s = "lambda.min", nIter = 20, intercept = FALSE) -->

<!-- plot(colMeans(x1)[cpop2_result], colMeans(x2)[cpop2_result]) -->
<!-- CPOP::identityDist(colMeans(x1)[cpop2_result], colMeans(x2)[cpop2_result]) -->
<!-- abline(a = 0, b = 1, col = "red") -->


<!-- cpop3_result = cpop3(x1, x2, y1, y2, cpop2_result = cpop2_result, intercept = FALSE) -->

<!-- plot(predict(cpop3_result$en1, newx = x1[,cpop2_result], s = "lambda.min"), -->
<!-- predict(cpop3_result$en2, newx = x1[,cpop2_result], s = "lambda.min")) -->
<!-- abline(a = 0, b = 1) -->

<!-- CPOP::identityDist( -->
<!-- predict(cpop3_result$en1, newx = x1[,cpop2_result], s = "lambda.min"), -->
<!-- predict(cpop3_result$en2, newx = x1[,cpop2_result], s = "lambda.min")) -->

<!-- CPOP::plot_cpop_coef(cpop3_result, type = "scatter") -->
<!-- CPOP::plot_cpop_coef(cpop3_result, type = "bar") -->
<!-- CPOP::plot_cpop_coef(cpop3_result, type = "text") -->
<!-- ``` -->


<!-- # Ridge on all features -->
<!-- ```{r} -->
<!-- lasso1 = glmnet::cv.glmnet( -->
<!--   x = x1, -->
<!--   y = y1, -->
<!--   family = "binomial", alpha = 0) -->

<!-- lasso2 = glmnet::cv.glmnet( -->
<!--   x = x2, -->
<!--   y = y2, -->
<!--   family = "binomial", alpha = 0) -->


<!-- plot(predict(lasso1, newx = x1, s = "lambda.min"), -->
<!--      predict(lasso2, newx = x1, s = "lambda.min")) -->
<!-- abline(a = 0, b = 1) -->

<!-- CPOP::identityDist( -->
<!--   predict(lasso1, newx = x1, s = "lambda.min"), -->
<!--   predict(lasso2, newx = x1, s = "lambda.min")) -->
<!-- ``` -->


<!-- # Ridge on Step1 features -->
<!-- ```{r} -->
<!-- lasso1 = glmnet::cv.glmnet( -->
<!--   x = x1[,cpop1_result], -->
<!--   y = y1, -->
<!--   family = "binomial", alpha = 0) -->

<!-- lasso2 = glmnet::cv.glmnet( -->
<!--   x = x2[,cpop1_result], -->
<!--   y = y2, -->
<!--   family = "binomial", alpha = 0) -->


<!-- plot(predict(lasso1, newx = x1[,cpop1_result], s = "lambda.min"), -->
<!--      predict(lasso2, newx = x1[,cpop1_result], s = "lambda.min")) -->
<!-- abline(a = 0, b = 1) -->

<!-- CPOP::identityDist( -->
<!--   predict(lasso1, newx = x1[,cpop1_result], s = "lambda.min"), -->
<!--   predict(lasso2, newx = x1[,cpop1_result], s = "lambda.min")) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- upper_elements = function(x){x[upper.tri(x)]} -->
<!-- ``` -->

<!-- ```{r} -->
<!-- boxplot( -->
<!--   upper_elements(cor(x1)) - upper_elements(cor(x2)), -->
<!--   upper_elements(cor(x1[,cpop1_result])) - upper_elements(cor(x2[,cpop1_result])), -->
<!--         upper_elements(cor(x1[,cpop2_result])) - upper_elements(cor(x2[,cpop2_result]))) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- sessionInfo() -->
<!-- ``` -->

